"""Shared declarative base and column mixins for ORM models.

The Alembic migration in alembic/versions/ is the schema's source of truth
(hand-written, not autogenerated from these models - see that file's
docstring for why); these models are kept matching it by hand, not the
other way round.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


class CreatedAtMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class UpdatedAtMixin:
    """Only for the tables contracts §3 lists with an updated_at column.

    `server_default=func.now()` alone would never change on UPDATE, so the
    migration also attaches a `set_updated_at()` trigger to every table using
    this mixin - see that migration's docstring. onupdate=func.now() here is
    a second line of defence for updates made through this ORM specifically;
    the trigger is what makes the column correct for any writer.
    """

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
