"""initial schema

Revision ID: 03296bf6e1b3
Revises:
Create Date: 2026-09-14 19:55:28.325406

Hand-written, not autogenerated from app/models/: autogenerate against
PostGIS-managed tables (spatial_ref_sys, geometry_columns, ...) emits
spurious drops for them, and won't emit CREATE EXTENSION at all. This is
the schema's source of truth (contracts §3); app/models/ is kept matching
it by hand.

One migration creating every table, including the M4 ones (papers,
paper_blocks, citations) — additive migrations later hurt far less than
rewrites once those tables are populated.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03296bf6e1b3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables that get an updated_at column per contracts §3's per-table listing
# (not every table — see e.g. profile_levels, which gets neither timestamp).
_TABLES_WITH_UPDATED_AT = ("users", "catalog_layers", "projects", "papers", "paper_blocks")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # DEFAULT now() only fires on INSERT — it would never actually update.
    # This trigger is what makes updated_at correct for any writer (ORM,
    # raw SQL, admin tools), not just app/models/base.py's onupdate=func.now(),
    # which only covers writes made through that specific ORM session.
    op.execute(
        """
        CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )

    # -- Identity ------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("email", sa.Text(), nullable=False, unique=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        # NULL for the Sprint-0 seeded user.
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "sessions",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # -- Catalog: the "what data do I have, and where" table ------------
    op.create_table(
        "catalog_layers",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("layer_id", sa.Text(), nullable=False, unique=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("variable", sa.Text(), nullable=True),
        sa.Column("units", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("depths", sa.dialects.postgresql.ARRAY(sa.dialects.postgresql.DOUBLE_PRECISION()), nullable=True),
        sa.Column("times", sa.dialects.postgresql.ARRAY(sa.TIMESTAMP(timezone=True)), nullable=True),
        sa.Column("value_min", sa.dialects.postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.Column("value_max", sa.dialects.postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.Column("default_colormap", sa.Text(), nullable=False, server_default="thermal"),
        sa.Column("object_path", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("licence", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    # Geometry column added via PostGIS's own function rather than as a
    # plain op.create_table column, so this migration has no import-time
    # dependency on geoalchemy2's Alembic integration — AddGeometryColumn is
    # what keeps geometry_columns/the PostGIS catalog consistent.
    op.execute("SELECT AddGeometryColumn('catalog_layers', 'bbox', 4326, 'POLYGON', 2)")

    # -- Observations -----------------------------------------------------
    op.create_table(
        "platforms",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("platform_id", sa.Text(), nullable=False, unique=True),
        sa.Column("platform_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "profiles",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("platform_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("platforms.id", ondelete="CASCADE"), nullable=False),
        sa.Column("observed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("cycle_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.execute("SELECT AddGeometryColumn('profiles', 'location', 4326, 'POINT', 2)")
    op.execute("ALTER TABLE profiles ALTER COLUMN location SET NOT NULL")
    op.execute("CREATE INDEX profiles_location_gix ON profiles USING GIST (location)")
    op.execute("CREATE INDEX profiles_observed_at_idx ON profiles (observed_at)")

    op.create_table(
        "profile_levels",
        # No created_at/updated_at: contracts §3 lists this table without
        # either, unlike the blanket "every table gets ..." sentence.
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("profile_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("profiles.id", ondelete="CASCADE"), nullable=False),
        sa.Column("depth", sa.dialects.postgresql.DOUBLE_PRECISION(), nullable=False),
        sa.Column("temperature", sa.dialects.postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.Column("salinity", sa.dialects.postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.Column("pressure", sa.dialects.postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.Column("qc_flag", sa.SmallInteger(), nullable=True),
    )
    op.execute("CREATE INDEX profile_levels_profile_idx ON profile_levels (profile_id, depth)")

    # -- Research workflow --------------------------------------------
    op.create_table(
        "projects",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("owner_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("visibility", sa.Text(), nullable=False, server_default="private"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "chat_nodes",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("project_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        # NULL for root; self-FK is fine inline in one CREATE TABLE — every
        # column, including this table's own id, is known within one statement.
        sa.Column("parent_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("chat_nodes.id", ondelete="CASCADE"), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_calls", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column("memory_mode", sa.Text(), nullable=False, server_default="isolated"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.execute("CREATE INDEX chat_nodes_parent_idx ON chat_nodes (parent_id)")

    op.create_table(
        "activities",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("project_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        sa.Column("chat_node_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("chat_nodes.id"), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # -- M4, defined now so migrations are additive, not rewrites ------
    op.create_table(
        "papers",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("project_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("visibility", sa.Text(), nullable=False, server_default="private"),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "paper_blocks",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("paper_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("papers.id", ondelete="CASCADE"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("block_type", sa.Text(), nullable=False),
        sa.Column("content", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("activity_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("activities.id"), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "citations",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("paper_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("papers.id", ondelete="CASCADE"), nullable=False),
        sa.Column("bibtex_key", sa.Text(), nullable=False),
        sa.Column("doi", sa.Text(), nullable=True),
        sa.Column("csl_json", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    for table in _TABLES_WITH_UPDATED_AT:
        op.execute(
            f"CREATE TRIGGER {table}_set_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )


def downgrade() -> None:
    # Reverse dependency order.
    op.drop_table("citations")
    op.drop_table("paper_blocks")
    op.drop_table("papers")
    op.drop_table("activities")
    op.drop_table("chat_nodes")
    op.drop_table("projects")
    op.drop_table("profile_levels")
    op.drop_table("profiles")
    op.drop_table("platforms")
    op.drop_table("catalog_layers")
    op.drop_table("sessions")
    op.drop_table("users")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # postgis/pgcrypto deliberately left in place: dropping postgis also
    # drops spatial_ref_sys/geometry_columns, which can fail against
    # anything else in the database still depending on them. Extensions
    # are a database-wide concern, not something one migration should undo.
